sudo: required
dist: trusty
language: c
compiler:
- clang
- gcc
cache: ccache
env:
- CPUX_BCLK=100

before_install:
- curl http://download.opensuse.org/repositories/home:/X0rg/xUbuntu_14.04/Release.key | sudo apt-key add -
- echo "deb http://download.opensuse.org/repositories/home:/X0rg/xUbuntu_14.04/ /" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
install:
- sudo apt-get install -y -qq nasm gettext libncursesw5-dev libcpuid-dev libpci-dev libprocps-dev libarchive-dev libncursesw5 libcpuid14 libpci3 libprocps3
before_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GTK=0 -DCMAKE_INSTALL_PREFIX=/usr ..
script:
- make -j $(nproc)
- cd ..
- if [[ $TRAVIS_OS_NAME == linux ]]; then
    bash -ex appimage.sh &&
    chmod +x ~/out/CPU-X*.AppImage &&
    wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh &&
    bash ./upload.sh ~/out/CPU-X*.AppImage;
  fi
after_success:
- cd build
- sudo make install
- sudo cpu-x --issue-fmt

notifications:
  slack:
    on_success: never
    on_failure: change
